print(1 + 2)
print(type(1 + 2))
print(1 + 2 ** 3)
print(type (1 + 2 ** 3))
print(15 / 2)
print(type(15 / 2))
print(15 // 2)
print(type(15 // 2))
print(15 % 2)
print(type(15 % 2))
print(type("Hello, World!"))
print("Hello, World!")
print("Hello, World!")
print("Hello, " + "World!")
print("Hello, ", "World!")